version: "3.9"
services:

  # server
  openvpn-server:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ./vpn/server/:/vpn
    ports:
      - "8080:1080"  # Changed from 1080:1080 to 8080:1080
  socks-server:
    image: serjs/go-socks5-proxy
    depends_on:
      - openvpn-server
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    network_mode: "service:openvpn-server"
    stdin_open: true
    tty: true

  # server1
  openvpn-server1:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ./vpn/server1/:/vpn
    ports:
      - "8081:1080"  # Changed from 1081:1080 to 8081:1080
    command: '-a ${SERVER1_EMAIL};${SERVER1_PASSWORD}'
  socks-server1:
    image: serjs/go-socks5-proxy
    depends_on:
      - openvpn-server1
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    network_mode: "service:openvpn-server1"
    stdin_open: true
    tty: true

  # server2
  openvpn-server2:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ./vpn/server2/:/vpn
    ports:
      - "8082:1080"  # Changed from 1082:1080 to 8083:1080
    command: '-a ${SERVER2_EMAIL};${SERVER2_PASSWORD}'
  socks-server2:
    image: serjs/go-socks5-proxy
    depends_on:
      - openvpn-server2
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    network_mode: "service:openvpn-server2"
    stdin_open: true
    tty: true

  # server3
  openvpn-server3:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ./vpn/server3/:/vpn
    ports:
      - "8083:1080"  # Changed from 1083:1080 to 8083:1080
    command: '-a ${SERVER3_EMAIL};${SERVER3_PASSWORD}'
  socks-server3:
    image: serjs/go-socks5-proxy
    depends_on:
      - openvpn-server3
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    network_mode: "service:openvpn-server3"
    stdin_open: true
    tty: true

  # server4
  openvpn-server4:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ./vpn/server4/:/vpn
    ports:
      - "8084:1080"  # Changed from 1082:1080 to 8084:1080
    command: '-a ${SERVER4_EMAIL};${SERVER4_PASSWORD}'
  socks-server4:
    image: serjs/go-socks5-proxy
    depends_on:
      - openvpn-server4
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    network_mode: "service:openvpn-server4"
    stdin_open: true
    tty: true

  # server5
  openvpn-server5:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ./vpn/server5/:/vpn
    ports:
      - "8085:1080"  # Changed from 1082:1080 to 8082:1080
    command: '-a ${SERVER5_EMAIL};${SERVER5_PASSWORD}'
  socks-server5:
    image: serjs/go-socks5-proxy
    depends_on:
      - openvpn-server5
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    network_mode: "service:openvpn-server5"
    stdin_open: true
    tty: true

  # server6
  openvpn-server6:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ./vpn/server6/:/vpn
    ports:
      - "8086:1080"  # Changed from 1082:1080 to 8082:1080
    command: '-a ${SERVER6_EMAIL};${SERVER6_PASSWORD}'
  socks-server6:
    image: serjs/go-socks5-proxy
    depends_on:
      - openvpn-server6
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    network_mode: "service:openvpn-server6"
    stdin_open: true
    tty: true

  # server7
  openvpn-server7:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ./vpn/server7/:/vpn
    ports:
      - "8087:1080"  # Changed from 1082:1080 to 8082:1080
    command: '-a ${SERVER7_EMAIL};${SERVER7_PASSWORD}'
  socks-server7:
    image: serjs/go-socks5-proxy
    depends_on:
      - openvpn-server7
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    network_mode: "service:openvpn-server7"
    stdin_open: true
    tty: true

  # server8
  openvpn-server8:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ./vpn/server8/:/vpn
    ports:
      - "8088:1080"  # Changed from 1082:1080 to 8082:1080
    command: '-a ${SERVER8_EMAIL};${SERVER8_PASSWORD}'
  socks-server8:
    image: serjs/go-socks5-proxy
    depends_on:
      - openvpn-server8
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    network_mode: "service:openvpn-server8"
    stdin_open: true
    tty: true

  # server9
  openvpn-server9:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ./vpn/server9/:/vpn
    ports:
      - "8089:1080"  # Changed from 1082:1080 to 8082:1080
    command: '-a ${SERVER9_EMAIL};${SERVER9_PASSWORD}'
  socks-server9:
    image: serjs/go-socks5-proxy
    depends_on:
      - openvpn-server9
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    network_mode: "service:openvpn-server9"
    stdin_open: true
    tty: true

  # server10
  openvpn-server10:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    read_only: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - ./vpn/server10/:/vpn
    ports:
      - "8010:1080"  # Changed from 1082:1080 to 8082:1080
    command: '-a ${SERVER10_EMAIL};${SERVER10_PASSWORD}'
  socks-server10:
    image: serjs/go-socks5-proxy
    depends_on:
      - openvpn-server10
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    network_mode: "service:openvpn-server10"
    stdin_open: true
    tty: true
